### ISSUE TITLE
Windows 10 Login page not showing

### ISSUE THREAD

**Issue by ZhangHanming** [Geraldcdx/IVLEDownloader#1]
The login page is blank on windows 10.

![wechat screenshot_20180825014321](https://user-images.githubusercontent.com/7940741/44599294-64413580-a808-11e8-9244-53219c268cc6.png)

**Comment by nerrons** [comment]
Can confirm this happens on my Windows 10 machine too.

**Comment by Geraldcdx** [comment]
IVLE crashes quite often! When it crashes, it results in this blank page. Just wait for a few minutes and it should work fine!

**Comment by friedsh2** [comment]
Login page is blank on Mac too :/

**Comment by Geraldcdx** [comment]
To clarify, once and for all, the login page works. 

It does not work when IVLE crashes. IVLE crashes more often then you expect. So check using a browser to see if IVLE is down. If it is down, try again later.

**Comment by friedsh2** [comment]
IVLE has never crashed before for me and yes I did check on a browser before, during and after I opened the IVLE downloader. However, the login page still remains blank. I don't know why is the blame being put on IVLE.

**Comment by friedsh2** [comment]
Maybe there are other steps or precautions needed to be taken in order to get the login page to work?

**Comment by tnctzn** [comment]
I've been having the same issue too on windows 10, is there any solution to this? I've tried multiple times too, even when IVLE is working in my browser. Would really appreciate it if anyone can provide a solution to this!

**Comment by nicholasleeeee** [comment]
Try reinstalling? I reinstalled on my windows 10 and it works. Also make sure you download the latest version, [v1.1]
